# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopoTijdreis
                                 A QGIS plugin
 This plugin loads all historic maps from 1815-2020 from topotijdreis.nl into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-09
        copyright            : (C) 2022 by A.G.J. Hullegie
        email                : ahullegie@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopoTijdreis class from file TopoTijdreis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .topo_tijdreis import TopoTijdreis
    return TopoTijdreis(iface)
